### ISSUE TITLE
IIIF resize request resulting in changing aspect ratio of image

### ISSUE THREAD

**Issue by beaudet** [ruven/iipsrv#77]
Please compare the output of these URLs which shows the aspect ratio of the image being changed when it shouldn't be  The server is using the latest build from code in github as of August 10, 2016.   The server has a MAX_CVT of 1024 configured.  Removing MAX_CVT resolves the problem on our test server.  I would argue that the MAX_CVT enforcement should be applied in such a way as to ensure that the aspect ratio of the resulting image remains unaltered.  The IIIF bounding box constraint seems to work properly so this problem seems to be limited to cases when only a single dimension is specified for the target size.

http://media.nga.gov/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/1000,/0/default.jpg
vs.
http://media.nga.gov/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/800,/0/default.jpg
vs.
http://media.nga.gov/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/full/0/default.jpg

Thanks,

Dave Beaudet, NGA

**Comment by nicolasfranck** [comment]
This depends on the syntax of the IIIF size parameter:

* w,h: in this case the w and h should be respected. Aspect ratio cannot be assured. This is used when the client application needs to put the image in a bounding box of the same width and height. Preserving the aspect ratio would break this. Use with care.

 I think the iipsrv should simply refuse to offer an image when width of height are above MAX_CVT (error message?).
 The code resets it now to MAX_SIZE, but that breaks the protocol, and leads to unexpected behaviour.

* !w,h: in this case the aspect ratio is preserved.

**Comment by beaudet** [comment]
Seems like an error might be OK (server 400 level? or redirect to MAX size?) provided the image metadata returned by info.json to clients is correct and already takes into account the MAX_CVT specified in the server configuration.  I agree that the aspect ratio cannot be honored if the client specifies both w and h, but if only dimension is requested, IIP should respect the aspect ratio (as well as MAX_CVT).  If that means returning an error rather than returning a morphed image, that's probably fine.

**Comment by beaudet** [comment]
Rob Sanderson responded to my request for comment on the IIIF Discuss list with the following.

I asked, while referencing this issue: Is the equivalent of IIP's MAX_CVT setting and the desired IIIF image server behavior in response to the condition described in the ticket [this issue] covered by the IIIF Image API?

Rob responded with:

Hi David,

It should be an error response. Exactly which error status code would depend on why the request is being rejected, and the implementation.

If you could get the image if you were authenticated but you're not, then it should be a 401.
Otherwise 403 if there's no way of getting access to it.

A generic 400 would probably serve well enough if there's a problem with using 403 and an existing authentication mechanism.
And a level 0 implementation will naively return 404, as it can't find the image file on disk.

(This is why we don't get very precise about error conditions in the spec!)

Rob

**Comment by beaudet** [comment]
Related to this issue is also a question of permissions.  The IIIF authentication API defines a mechanism for IIIF clients to interact with auth/authnz services for images in order to ensure that the proper images and sizes are served.  Currently the most straightforward way to provide a IIIF Auth implementation for images with multiple sizes is to produce multiple zoomable source images.  It would be great if image servers could support the notion of a downgraded image on a per image basis, perhaps by the presence of environmental variables defined within the request scope.  In that manner, an auth API implementation could enable an image server to feed multiple maximum sizes for the same image resource.  The auth API implementation would of course need to interface with permission sources, authentication and authorization services, etc.  I believe that having support for per request maximum sizes in the image server component would make IIIF auth implementations much easier and would eliminate the need to produce multiple zoom image sizes for the same resource.  This dovetails with the max size settings in info.json.  The max would be either max cvt or the per image maximum if one is set in the request.

**Comment by ruven** [comment]
I've now committed a fix for this and the aspect ratio is now respected in these cases. I prefer not to send an error in this scenario even if this would be more "correct" so that the user will at least get something useful back. Please test it out and tell me if it's OK now.

**Comment by beaudet** [comment]
Ruven, I recompiled using your latest code from master but no luck when accessing images using the IIIF protocol.  The images being produced are still having their aspect ratio changed when MAX_CVT is set (in this case to 1024):

HERE IS A REQUEST FOR "FULL SIZE" - and in this case, the image is getting scaled properly - to a max height of 1024 as per MAX_CVT
curl -q -k https://myserver/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/full/0/default.jpg > /tmp/myfile.jpg; identify /tmp/myfile.jpg;
/tmp/myfile.jpg JPEG 790x1024 790x1024+0+0 8-bit DirectClass 110KB 0.000u 0:00.000

THE REQUEST BELOW SHOULD PRODUCE THE SAME OUTPUT AS ABOVE WHEN MAX_CVT = 1024 - it asks to scale the image such that it's width is exactly 1024 - the width is correct but the height calculation required to maintain the aspect ratio does not appear to be.  In this case, the height would actually be > 1024 after height scaling which would violate MAX_CVT - so... it would seem in such cases, the safest thing to do if you don't thrown an error is to return an image with width < 1024 and let the MAX_CVT on height be the driving factor for scaling.  I think either way, you're going to violate the protocol by not returning an error, but it's probably better to violate the protocol by returning a smaller, properly scaled image rather than a properly sized, but distorted one in this case.

curl -q -k https://myserver/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/1024,/0/default.jpg > /tmp/myfile.jpg; identify /tmp/myfile.jpg;
/tmp/myfile.jpg JPEG 1024x1024 1024x1024+0+0 8-bit DirectClass 166KB 0.000u 0:00.000

From the table in section 4.2 of the IIIF Image API:
w,	The image or region should be scaled so that its width is exactly equal to w, and the height will be a calculated value that maintains the aspect ratio of the extracted region.

,h	The image or region should be scaled so that its height is exactly equal to h, and the width will be a calculated value that maintains the aspect ratio of the extracted region.

**Comment by ruven** [comment]
This seems to work as you want on my test machine. Are you sure you're running the latest version?

**Comment by beaudet** [comment]
Quite sure, but I'll double check.

**Comment by beaudet** [comment]
I just re-cloned from scratch, autoconfed, configured, and installed to my fastcgi directory, restarted http and varnish, and the aspect ratio continues to be altered with the "w," IIIF option.  If you can send me a RHEL6 compatible executable without Kakadu, I can try it with our setup to see if it works.  I'll also send you one of these images so you can try on your end.

**Comment by ruven** [comment]
OK, I've rewritten the fix and, effectively, there was indeed a problem. I've just committed some new code that should now work properly. Please try it and confirm whether it works for you.

**Comment by beaudet** [comment]
I'm now getting the message on screen and in the logs "IIIF: invalid size" when trying to access a URL like:

https://myserver/iiif/public/objects/7/9/79-primary-0-nativeres.ptif/full/300,/0/default.jpg

**Comment by ruven** [comment]
OK, 3rd time lucky I hope! Try this new commit.

**Comment by beaudet** [comment]
Indeed.  Seems to be working now.  Thanks Ruven.  I might have a pull request in the near future that checks for the presence of MAX_CVT in the environment within the FCGI Accept loop.  That would enable a filter to check the permissions of the image being requested and to set a different MAX_CVT for that specific request.  I'll create a separate issue for that if you think it's a good idea.

**Comment by ruven** [comment]
How would you communicate the permissions for the image?

**Comment by beaudet** [comment]
By "permissions" I mean what is the maximum size of the original PTIF I'd like to expose publicly.  In some cases, it might just be a small thumbnail, in other cases, a size suitable for display on a web page, and in other cases, full zooming capabilities.   And I'd like to use a single full size PTIF to service all of these requests with IIP producing the derivatives dynamically over the IIIF protocol.

As I think more about this, it's not really something currently supported by MAX_CVT actually.  MAX_CVT is mostly a performance / anti-DOS setting.  What I'd really like to be able to do is to tell IIP to treat the source PTIF as if it's actually smaller than the source.  So, if I have a 12000x12000 image, I'd like to be able to tell IIP for a certain web request to treat that image as if it's actually only 2000x2000.  That restriction would extend down to the generation of zoom tiles thereby limiting the ability to zoom any deeper than the pixels in the 2000x2000 version.  MAX_CVT doesn't currently prevent that.

Do you think that's feasible?  If not, it seems that multiple PTIF derivatives would need to be created - I'm trying to minimize the number of derivatives and to rely on a robust caching strategy to ensure performance.

**Comment by ruven** [comment]
No, you're right, MAX_CVT only supports a global export size limit and so won't limit tiles requests. The other issue is how to tell iipsrv what the limit what be. Would this again be global per iipsrv instance? Or using some kind of authentication system? If per instance,

I guess I could introduce a new MAX_ZOOM limit or similar which would virtually limit the available image size. To make this easier to implement it the max available size would be the highest existing resolution level within your size limit.

**Comment by beaudet** [comment]
I think supporting the setting of an environmental variable per request (to override a global default) would work fine.  I tested this out with a hack to how MAX_CVT is retrieved and it works - the FGCI:getParam() call just has to be made within the accept loop.  

This would provide a lot of flexibility for a wide variety of implementations I think.  There are plenty of Apache modules for turning request parameters and/or URLs into environmental variables and requests could be pushed through a proxy to determine the appropriate permissions for the user accessing the services.  It could transparently proxy to IIP which could be locked down to localhost. There's also the possibility of writing an Apache input filter.  Any of these could set a MAX_ZOOM and MAX_CVT environment variable which would be picked up by IIP.

It's worth reading through the IIIF authentication API as well.  The info.json service is affected by the IIIF API.  The MAX_ZOOM and MAX_CVT also have an effect on info.json.  I imagine that someone implementing the IIIF API (currently very site-specific custom work) would handle the initial request, perform authentication and permission checks, query IIIF for info.json after setting MAX_CVT and MAX_ZOOM, and proxy image requests to IIP.
